# Generated by Django 5.0.3 on 2026-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='ema_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='histograma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='macd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='sma_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='sma_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='volatilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
