# Generated by Django 5.0.3 on 2026-05-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargar', '0004_empresa_stockdata_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='ema_10',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='histograma',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='macd',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='rsi',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='sma_10',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='sma_30',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volatilidad',
        ),
    ]
