# Generated by Django 5.0.3 on 2026-06-24 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargar', '0005_remove_stockdata_ema_10_remove_stockdata_histograma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('precio_actual', models.FloatField()),
                ('precio_predicho', models.FloatField()),
                ('retorno', models.FloatField()),
                ('senal', models.CharField(max_length=50)),
                ('tendencia', models.CharField(max_length=50)),
                ('interpretacion', models.TextField()),
                ('riesgo', models.CharField(max_length=50)),
                ('recomendacion', models.TextField()),
                ('rsi', models.FloatField()),
                ('estado_rsi', models.CharField(max_length=30)),
                ('macd', models.FloatField()),
                ('estado_macd', models.CharField(max_length=30)),
                ('sma10', models.FloatField()),
                ('sma30', models.FloatField()),
                ('score_ia', models.FloatField()),
                ('nivel_ia', models.CharField(max_length=50)),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargar.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
